### create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "hashedandsalted@email.com",
  "password": "hashedpassword"
}

### Sighin with a created user
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "hashedandsalted@email.com",
  "password": "hashedpassword"
}

### find a particular user with a given ID
GET http://localhost:3000/auth/2

### find all users with a given email
GET http://localhost:3000/auth?email=changedupdated@email.com

### remove a particular user with a given ID
DELETE http://localhost:3000/auth/3

### update a user
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "email": "changedupdated@email.com"
}
