### create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "deleteme@email.com",
  "password": "testing123"
}

### find a particular user with a given ID
GET http://localhost:3000/auth/1

### find all users with a given email
GET http://localhost:3000/auth?email=deleteme@email.com

### remove a particular user with a given ID
DELETE http://localhost:3000/auth/3
